// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/webook/comment/grpc"
	"webook/webook/comment/ioc"
	"webook/webook/comment/repository"
	"webook/webook/comment/repository/dao"
	"webook/webook/comment/service"
)

// Injectors from wire.go:

func Init() *App {
	db := ioc.InitDB()
	commentDAO := dao.NewCommentDAO(db)
	logger := ioc.InitLogger()
	commentRepository := repository.NewCommentRepo(commentDAO, logger)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc.NewGrpcServer(commentService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(commentServiceServer, client, logger)
	app := &App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewCommentDAO, repository.NewCommentRepo, service.NewCommentSvc, grpc.NewGrpcServer)

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitEtcdClient)
