// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/webook/comment/grpc"
	"webook/webook/comment/ioc"
	"webook/webook/comment/repository"
	"webook/webook/comment/repository/dao"
	"webook/webook/comment/service"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB()
	commentDAO := dao.NewCommentDAO(db)
	commentRepository := repository.NewCommentRepo(commentDAO, logger)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc.NewGrpcServer(commentService)
	server := ioc.InitGRPCxServer(commentServiceServer, logger)
	app := &App{
		GRPCServer: server,
	}
	return app
}
