// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/webook/reward/grpc"
	"webook/webook/reward/ioc"
	"webook/webook/reward/repository"
	"webook/webook/reward/repository/cache"
	"webook/webook/reward/repository/dao"
	"webook/webook/reward/service"
)

// Injectors from wire.go:

func Init() *App {
	client := ioc.InitEtcdClient()
	wechatPaymentServiceClient := ioc.InitPaymentClient(client)
	db := ioc.InitDB()
	rewardDAO := dao.NewRewardGORMDAO(db)
	cmdable := ioc.InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	logger := ioc.InitLogger()
	accountServiceClient := ioc.InitAccountClient(client)
	wechatNativeRewardService := service.NewWechatNativeRewardService(wechatPaymentServiceClient, rewardRepository, logger, accountServiceClient)
	rewardServiceServer := grpc.NewRewardServiceServer(wechatNativeRewardService)
	server := ioc.InitGRPCxServer(rewardServiceServer, logger)
	saramaClient := ioc.InitKafka()
	paymentEventConsumer := ioc.InitPaymentEventConsumer(saramaClient, logger, wechatNativeRewardService)
	app := &App{
		GRPCServer: server,
		Consumer:   paymentEventConsumer,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitRedis, ioc.InitKafka)
