// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"webook/webook/tag/events"
	"webook/webook/tag/grpc"
	"webook/webook/tag/repository/cache"
	"webook/webook/tag/repository/dao"
	"webook/webook/tag/service"
)

// Injectors from wire.go:

// InitGRPCService 初始化集成测试用的 Tag gRPC 服务。
func InitGRPCService(p events.Producer) *grpc.TagServiceServer {
	gormDB := InitTestDB()
	tagDAO := dao.NewGORMTagDAO(gormDB)
	cmdable := InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	logger := InitLog()
	tagRepository := InitRepository(tagDAO, tagCache, logger)
	tagService := service.NewTagService(tagRepository, p, logger)
	tagServiceServer := grpc.NewTagServiceServer(tagService)
	return tagServiceServer
}
