// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/webook/tag/events"
	"webook/webook/tag/grpc"
	"webook/webook/tag/ioc"
	"webook/webook/tag/repository/cache"
	"webook/webook/tag/repository/dao"
	"webook/webook/tag/service"
)

// Injectors from wire.go:

func Init() *App {
	db := ioc.InitDB()
	tagDAO := dao.NewGORMTagDAO(db)
	cmdable := ioc.InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	logger := ioc.InitLogger()
	tagRepository := ioc.InitRepository(tagDAO, tagCache, logger)
	client := ioc.InitKafka()
	syncProducer := ioc.InitSyncProducer(client)
	producer := events.NewSaramaSyncProducer(syncProducer)
	tagService := service.NewTagService(tagRepository, producer, logger)
	tagServiceServer := grpc.NewTagServiceServer(tagService)
	server := ioc.InitGRPCxServer(tagServiceServer, logger)
	app := &App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMTagDAO, cache.NewRedisTagCache, ioc.InitRepository, events.NewSaramaSyncProducer, service.NewTagService, grpc.NewTagServiceServer)

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger, ioc.InitKafka, ioc.InitSyncProducer)
