// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"webook/webook/api/proto/gen/account/v1"
	"webook/webook/api/proto/gen/payment/v1"
	"webook/webook/reward/repository"
	"webook/webook/reward/repository/cache"
	"webook/webook/reward/repository/dao"
	"webook/webook/reward/service"
)

// Injectors from wire.go:

func InitWechatNativeSvc(client pmtv1.WechatPaymentServiceClient) *service.WechatNativeRewardService {
	gormDB := InitTestDB()
	rewardDAO := dao.NewRewardGORMDAO(gormDB)
	cmdable := InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	logger := InitLogger()
	accountServiceClient := InitNilAccountClient()
	wechatNativeRewardService := service.NewWechatNativeRewardService(client, rewardRepository, logger, accountServiceClient)
	return wechatNativeRewardService
}

// wire.go:

var thirdPartySet = wire.NewSet(InitTestDB, InitLogger, InitRedis)

func InitNilAccountClient() accountv1.AccountServiceClient {
	return nil
}
