// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/webook/payment/ioc"
	"webook/webook/payment/web"
)

// Injectors from wire.go:

func InitApp() *App {
	wechatConfig := ioc.InitWechatConfig()
	handler := ioc.InitWechatNotifyHandler(wechatConfig)
	nativePaymentService := ioc.InitNilNativePaymentService()
	loggerV1 := ioc.InitLogger()
	wechatHandler := web.NewWechatHandler(handler, nativePaymentService, loggerV1)
	server := ioc.InitGinServer(wechatHandler)
	app := &App{
		WebServer: server,
	}
	return app
}
