// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/webook/account/grpc"
	"webook/webook/account/ioc"
	"webook/webook/account/repository"
	"webook/webook/account/repository/cache"
	"webook/webook/account/repository/dao"
	"webook/webook/account/service"
)

// Injectors from wire.go:

func Init() *App {
	db := ioc.InitDB()
	accountDAO := dao.NewCreditGORMDAO(db)
	cmdable := ioc.InitRedis()
	cacheCache := cache.NewRedisCache(cmdable)
	accountRepository := repository.NewAccountRepository(accountDAO, cacheCache)
	accountService := service.NewAccountService(accountRepository)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	logger := ioc.InitLogger()
	server := ioc.InitGRPCxServer(accountServiceServer, logger)
	app := &App{
		GRPCServer: server,
	}
	return app
}
