// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	article3 "webook/webook/internal/events/article"
	"webook/webook/internal/pkg/logger"
	"webook/webook/internal/pkg/ratelimit"
	"webook/webook/internal/repository"
	article2 "webook/webook/internal/repository/article"
	"webook/webook/internal/repository/cache"
	"webook/webook/internal/repository/dao"
	"webook/webook/internal/repository/dao/article"
	"webook/webook/internal/service"
	"webook/webook/internal/web"
	"webook/webook/internal/web/jwt"
	"webook/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	cmdable := ioc.InitRedis()
	limitParam := ioc.InitLimitParam()
	duration := limitParam.Interval
	int2 := limitParam.Rate
	redisSlideWindowLimiter := ratelimit.NewRedisSlideWindowLimiter(cmdable, duration, int2)
	redisJwt := jwt.NewRedisJwt(cmdable)
	zapLogger := ioc.InitLogger()
	loggerZapLogger := logger.NewZapLogger(zapLogger)
	v := ioc.InitMiddleWare(redisSlideWindowLimiter, redisJwt, loggerZapLogger)
	db := ioc.InitDB(loggerZapLogger)
	gormUserDAO := dao.NewUserDAO(db)
	redisUserCache := cache.NewUserCache(cmdable)
	cacheUserRepository := repository.NewUserRepository(gormUserDAO, redisUserCache)
	userService := service.NewUserService(cacheUserRepository, loggerZapLogger)
	redisCodeCache := cache.NewCodeCache(cmdable)
	cacheCodeRepository := repository.NewCodeRepository(redisCodeCache)
	smsService := ioc.InitSMSService(cmdable)
	codeService := service.NewCodeService(cacheCodeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, redisJwt, cmdable)
	wechatService := ioc.InitWeChatService()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, redisJwt)
	articleGormDao := article.NewArticleGormDao(db)
	redisArticleCache := cache.NewRedisArticleCache(cmdable)
	cachedArticleRepository := article2.NewCachedArticleRepository(articleGormDao, cacheUserRepository, redisArticleCache, loggerZapLogger)
	client := ioc.InitKafka()
	syncProducer := ioc.NewSyncProducer(client)
	producer := article3.NewKafkaProducer(syncProducer)
	iArticleService := service.NewArticleService(cachedArticleRepository, loggerZapLogger, producer)
	clientv3Client := ioc.InitEtcd()
	interactiveServiceClient := ioc.InitIntrGRPCClientV1(clientv3Client)
	rewardServiceClient := ioc.InitRewardGRPCClient(clientv3Client)
	articleHandler := web.NewArticleHandler(iArticleService, interactiveServiceClient, rewardServiceClient, loggerZapLogger)
	rewardHandler := web.NewRewardHandler(rewardServiceClient)
	rankingRedisCache := cache.NewRankingRedisCache(cmdable)
	rankingLocalCache := cache.NewRankingLocalCache()
	rankingRepository := repository.NewCachedRankingRepository(rankingRedisCache, rankingLocalCache)
	rankingService := service.NewBatchRankingService(iArticleService, rankingRepository, interactiveServiceClient)
	rankingHandler := web.NewRankingHandler(rankingService)
	engine := ioc.InitGin(v, userHandler, oAuth2WechatHandler, articleHandler, rewardHandler, rankingHandler)
	v2 := ioc.NewConsumers()
	rlockClient := ioc.InitRLockClient(cmdable)
	rankingJob := ioc.InitRankingJob(rankingService, rlockClient, loggerZapLogger)
	cron := ioc.InitJobs(loggerZapLogger, rankingJob)
	localFuncExecutor := ioc.InitLocalFuncExecutor(rankingService)
	jobDAO := dao.NewGORMJobDAO(db)
	jobRepository := repository.NewPreemptCronJobRepository(jobDAO)
	jobService := service.NewCronJobService(jobRepository, loggerZapLogger)
	scheduler := ioc.InitScheduler(loggerZapLogger, localFuncExecutor, jobService)
	app := &App{
		web:       engine,
		consumers: v2,
		cron:      cron,
		scheduler: scheduler,
	}
	return app
}

func InitArticleHandler(artDAO article.ArticleDao) *web.ArticleHandler {
	zapLogger := ioc.InitLogger()
	loggerZapLogger := logger.NewZapLogger(zapLogger)
	db := ioc.InitDB(loggerZapLogger)
	gormUserDAO := dao.NewUserDAO(db)
	cmdable := ioc.InitRedis()
	redisUserCache := cache.NewUserCache(cmdable)
	cacheUserRepository := repository.NewUserRepository(gormUserDAO, redisUserCache)
	redisArticleCache := cache.NewRedisArticleCache(cmdable)
	cachedArticleRepository := article2.NewCachedArticleRepository(artDAO, cacheUserRepository, redisArticleCache, loggerZapLogger)
	producer := article3.NewNoOpProducer()
	iArticleService := service.NewArticleService(cachedArticleRepository, loggerZapLogger, producer)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerZapLogger)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerZapLogger)
	interactiveServiceClient := ioc.InitIntrGRPCClient(interactiveService)
	rewardServiceClient := ioc.InitNilRewardGRPCClient()
	articleHandler := web.NewArticleHandler(iArticleService, interactiveServiceClient, rewardServiceClient, loggerZapLogger)
	return articleHandler
}

func InitInteractiveService() service.InteractiveService {
	zapLogger := ioc.InitLogger()
	loggerZapLogger := logger.NewZapLogger(zapLogger)
	db := ioc.InitDB(loggerZapLogger)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerZapLogger)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerZapLogger)
	return interactiveService
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger, ioc.InitKafka, ioc.NewSyncProducer)

var interactiveSvcProvider = wire.NewSet(service.NewInteractiveService, repository.NewCachedInteractiveRepository, dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache)

var rankingServiceSet = wire.NewSet(repository.NewCachedRankingRepository, cache.NewRankingRedisCache, cache.NewRankingLocalCache, service.NewBatchRankingService)

var jobProviderSet = wire.NewSet(dao.NewGORMJobDAO, repository.NewPreemptCronJobRepository, service.NewCronJobService, ioc.InitLocalFuncExecutor, ioc.InitScheduler)
