// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"webook/webook/internal/pkg/logger"
	"webook/webook/internal/pkg/ratelimit"
	"webook/webook/internal/repository"
	article2 "webook/webook/internal/repository/article"
	"webook/webook/internal/repository/cache"
	"webook/webook/internal/repository/dao"
	"webook/webook/internal/repository/dao/article"
	"webook/webook/internal/service"
	"webook/webook/internal/web"
	"webook/webook/internal/web/jwt"
	"webook/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	limitParam := ioc.InitLimitParam()
	duration := limitParam.Interval
	int2 := limitParam.Rate
	redisSlideWindowLimiter := ratelimit.NewRedisSlideWindowLimiter(cmdable, duration, int2)
	redisJwt := jwt.NewRedisJwt(cmdable)
	zapLogger := ioc.InitLogger()
	loggerZapLogger := logger.NewZapLogger(zapLogger)
	v := ioc.InitMiddleWare(redisSlideWindowLimiter, redisJwt, loggerZapLogger)
	db := ioc.InitDB(loggerZapLogger)
	gormUserDAO := dao.NewUserDAO(db)
	redisUserCache := cache.NewUserCache(cmdable)
	cacheUserRepository := repository.NewUserRepository(gormUserDAO, redisUserCache)
	userService := service.NewUserService(cacheUserRepository, loggerZapLogger)
	redisCodeCache := cache.NewCodeCache(cmdable)
	cacheCodeRepository := repository.NewCodeRepository(redisCodeCache)
	smsService := ioc.InitSMSService(cmdable)
	codeService := service.NewCodeService(cacheCodeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, redisJwt, cmdable)
	wechatService := ioc.InitWeChatService()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, redisJwt)
	articleGormDao := article.NewArticleGormDao(db)
	redisArticleCache := cache.NewRedisArticleCache(cmdable)
	cachedArticleRepository := article2.NewCachedArticleRepository(articleGormDao, cacheUserRepository, redisArticleCache, loggerZapLogger)
	iArticleService := service.NewArticleService(cachedArticleRepository)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerZapLogger)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerZapLogger)
	articleHandler := web.NewArticleHandler(iArticleService, interactiveService, loggerZapLogger)
	engine := ioc.InitGin(v, userHandler, oAuth2WechatHandler, articleHandler)
	return engine
}

func InitArticleHandler(artDAO article.ArticleDao) *web.ArticleHandler {
	zapLogger := ioc.InitLogger()
	loggerZapLogger := logger.NewZapLogger(zapLogger)
	db := ioc.InitDB(loggerZapLogger)
	gormUserDAO := dao.NewUserDAO(db)
	cmdable := ioc.InitRedis()
	redisUserCache := cache.NewUserCache(cmdable)
	cacheUserRepository := repository.NewUserRepository(gormUserDAO, redisUserCache)
	redisArticleCache := cache.NewRedisArticleCache(cmdable)
	cachedArticleRepository := article2.NewCachedArticleRepository(artDAO, cacheUserRepository, redisArticleCache, loggerZapLogger)
	iArticleService := service.NewArticleService(cachedArticleRepository)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerZapLogger)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerZapLogger)
	articleHandler := web.NewArticleHandler(iArticleService, interactiveService, loggerZapLogger)
	return articleHandler
}

func InitInteractiveService() service.InteractiveService {
	zapLogger := ioc.InitLogger()
	loggerZapLogger := logger.NewZapLogger(zapLogger)
	db := ioc.InitDB(loggerZapLogger)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerZapLogger)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerZapLogger)
	return interactiveService
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger)

var interactiveSvcProvider = wire.NewSet(service.NewInteractiveService, repository.NewCachedInteractiveRepository, dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache)
