// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"webook/webook/comment/grpc"
	"webook/webook/comment/repository"
	"webook/webook/comment/repository/dao"
	"webook/webook/comment/service"
	"webook/webook/internal/pkg/logger"
)

// Injectors from wire.go:

func InitGRPCServer() *grpc.CommentServiceServer {
	gormDB := InitTestDB()
	commentDAO := dao.NewCommentDAO(gormDB)
	loggerV1 := logger.NewNoOpLogger()
	commentRepository := repository.NewCommentRepo(commentDAO, loggerV1)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc.NewGrpcServer(commentService)
	return commentServiceServer
}
