// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"webook/webook/follow/grpc"
	"webook/webook/follow/repository"
	"webook/webook/follow/repository/cache"
	"webook/webook/follow/repository/dao"
	"webook/webook/follow/service"
	"webook/webook/internal/pkg/logger"
)

// Injectors from wire.go:

func InitServer() *grpc.FollowServiceServer {
	gormDB := InitTestDB()
	followRelationDao := dao.NewGORMFollowRelationDAO(gormDB)
	cmdable := InitRedis()
	followCache := cache.NewRedisFollowCache(cmdable)
	loggerLogger := logger.NewNoOpLogger()
	followRepository := repository.NewFollowRelationRepository(followRelationDao, followCache, loggerLogger)
	followRelationService := service.NewFollowRelationService(followRepository)
	followServiceServer := grpc.NewFollowRelationServiceServer(followRelationService)
	return followServiceServer
}
