// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"webook/webook/payment/events"
	"webook/webook/payment/ioc"
	"webook/webook/payment/repository"
	"webook/webook/payment/repository/dao"
	"webook/webook/payment/service/wechat"
)

// Injectors from wire.go:

func InitWechatNativeService() *wechat.NativePaymentService {
	wechatConfig := ioc.InitWechatConfig()
	client := ioc.InitWechatClient(wechatConfig)
	gormDB := InitTestDB()
	paymentDAO := dao.NewPaymentGORMDAO(gormDB)
	paymentRepository := repository.NewPaymentRepository(paymentDAO)
	logger := ioc.InitLogger()
	producer := InitNopProducer()
	nativePaymentService := ioc.InitWechatNativeService(client, paymentRepository, logger, producer, wechatConfig)
	return nativePaymentService
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitLogger, InitTestDB)

func InitNopProducer() events.Producer {
	return events.NopProducer{}
}

var wechatNativeSvcSet = wire.NewSet(ioc.InitWechatClient, dao.NewPaymentGORMDAO, repository.NewPaymentRepository, InitNopProducer, ioc.InitWechatNativeService, ioc.InitWechatConfig)
