// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"webook/webook/follow/grpc"
	"webook/webook/follow/ioc"
	"webook/webook/follow/repository"
	"webook/webook/follow/repository/cache"
	"webook/webook/follow/repository/dao"
	"webook/webook/follow/service"
)

// Injectors from wire.go:

func Init() *App {
	db := ioc.InitDB()
	followRelationDao := dao.NewGORMFollowRelationDAO(db)
	cmdable := ioc.InitRedis()
	followCache := cache.NewRedisFollowCache(cmdable)
	logger := ioc.InitLogger()
	followRepository := repository.NewFollowRelationRepository(followRelationDao, followCache, logger)
	followRelationService := service.NewFollowRelationService(followRepository)
	followServiceServer := grpc.NewFollowRelationServiceServer(followRelationService)
	server := ioc.InitGRPCxServer(followServiceServer, logger)
	app := &App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMFollowRelationDAO, cache.NewRedisFollowCache, repository.NewFollowRelationRepository, service.NewFollowRelationService, grpc.NewFollowRelationServiceServer)

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitLogger)
